# Generated by Django 4.1.4 on 2023-01-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("purchaseID", models.AutoField(primary_key=True, serialize=False)),
                ("deliveryAddress", models.CharField(max_length=255)),
                ("deliveryDate", models.CharField(max_length=15)),
                ("clientName", models.CharField(max_length=255)),
                ("totalPrice", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("itemID", models.AutoField(primary_key=True, serialize=False)),
                ("itemName", models.CharField(max_length=255)),
                ("itemQuantity", models.IntegerField()),
                ("unitPrice", models.FloatField()),
                (
                    "purchaseID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                ("deliveryID", models.AutoField(primary_key=True, serialize=False)),
                ("deliveryAddress", models.CharField(max_length=255)),
                ("deliveryDate", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Verified", "Verified")],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                (
                    "purchaseID",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
