# Generated by Django 4.1.4 on 2023-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventory_restockorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Disapproved', 'Disapproved')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='restockorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Disapproved', 'Disapproved')], default='Pending', max_length=15),
        ),
    ]
